import { Space_Grotesk } from 'next/font/google'
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import 'aos/dist/aos.css';
import "/public/style/swiper/swiper-bundle.min.css"
import "/public/assets/font/font-awesome.css"
import "/public/assets/font/spunky.css"
// import "/public/style/bootstrap/css/bootstrap.css"
import "/public/style/dist/app.css"
import Head from "next/head";
import Script from "next/script";

export const metadata = {
    title: 'Spunky SDX - a ground-breaking, decentralized multi-chain meme token designed to address the loss of assets to theft in the crypto space',
    description: 'Generated by create next app',
}


const grotesk = Space_Grotesk({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--grotesk",
    display: 'swap',
})



export default function RootLayout({ children }) {
    return (

     

        <html lang="en">
               <Head>
        <meta name="description" content="Spunky SDX" />
        <meta property="og:title" content="Spunky SDX" />
        <meta property="og:description" content="Best Blockchain minning" />
        <meta property="og:image" content="https://spunkysdx.io" />
        <meta property="og:url" content="https://spunkysdx.io" />
        <meta
          name="SpunkySDX"
          content="SpunkySDX leverages an inbuilt advanced Artificial Intelligence(AI)- based tool to track stolen cryptocurrency tokens/coins across different Ethereum Virtual Machine (EVM) compatible blockchains, from Decentralized wallets to Centralized Exchanges (CEX)."
        />
        <link rel="canonical" href="https://spunkysdx.io" />
        <meta name="robots" content="Staking, yield, interest, accumulat " />
        <meta
          name="keywords"
          content="Asset tracking, AI tools, best meme coin, Bull Run  , crypto, web3, chatbot, secured, decentralized, centralised, bag more, standard, minted, mining,Portfolio, accurate, speed, utility, used cases, EVM "
        />

        <link
          rel="icon"
          href="/assets/img/logo/spdx-logo.png"
          type="image/png"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />

        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-2KZ9EH1B33"
          strategy="afterInteractive"
        />
        <Script strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments)}
          gtag('js', new Date());

          gtag('config', 'G-2KZ9EH1B33');
        `}
        </Script>
      </Head>
     
            <body className={`${grotesk.variable} header-fixed page-loaded`}>{children}</body>
        </html>
    )
}
